package ihm;

import application.Appli;
import metier.Vip;
import modele.ModeleJTable;

import javax.swing.*;
import java.sql.SQLException;

public class FenetreApplication extends javax.swing.JFrame {

    private ModeleJTable leModele;

    public FenetreApplication() throws Exception {

        ImageIcon img = new ImageIcon("Icon.png");
        this.setIconImage(img.getImage());

        // instanciation du modele de données de la JTable
        this.leModele = new ModeleJTable();
        // initialisation des composants
        initComponents();
        Appli.centreWindow(this);
        // affichage
        try {
            leModele.chargerLesVips();
        } catch (SQLException ex) {
            System.out.println(" Erreur au chargement : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        laTable = new javax.swing.JTable();
        jpGestion = new javax.swing.JPanel();
        btInserer = new javax.swing.JButton();
        btnModifierVIP = new javax.swing.JButton();
        btPhoto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VIPs");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        laTable.setModel(leModele);
        laTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        laTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laTable);

        jpGestion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Gestion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 10))); // NOI18N

        btInserer.setText("Inserer");
        btInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsererActionPerformed(evt);
            }
        });

        btnModifierVIP.setText("Modifier VIP");
        btnModifierVIP.setEnabled(false);
        btnModifierVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierVIPActionPerformed(evt);
            }
        });

        btPhoto.setText("Photos");
        btPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPhotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGestionLayout = new javax.swing.GroupLayout(jpGestion);
        jpGestion.setLayout(jpGestionLayout);
        jpGestionLayout.setHorizontalGroup(
                jpGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpGestionLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(btInserer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(btnModifierVIP)
                                .addGap(50, 50, 50)
                                .addComponent(btPhoto)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpGestionLayout.setVerticalGroup(
                jpGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jpGestionLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jpGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btInserer)
                                        .addComponent(btnModifierVIP)
                                        .addComponent(btPhoto))
                                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Liste des VIPs :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                                                .addComponent(jpGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jpGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsererActionPerformed
        Vip vip = new Vip(0, null, null, null);
        FenetreSaisieVip laSaisie = new FenetreSaisieVip(this, vip);
        if (laSaisie.doModal() == true) {
            try {
                leModele.chargerLesVips();
            } catch (Exception e) {
                System.out.println("pas possible");
            }
        }
    }//GEN-LAST:event_btInsererActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vraiment sortir ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (reponse == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnModifierVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierVIPActionPerformed
        int ligneSelectionne = laTable.getSelectedRow();
        //on récupére la valeur de la première colonne de la ligne sélectionné
        int numero = (int) laTable.getValueAt(ligneSelectionne, 0);

        FenetreMariageVIP fMariage = null;
        try {
            fMariage = new FenetreMariageVIP(this, numero);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
        if (fMariage.doModal() == true) {
            try {
                System.out.println("chargement des vips...");
                leModele.chargerLesVips();
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        btnModifierVIP.setEnabled(false);
    }//GEN-LAST:event_btnModifierVIPActionPerformed

    private void laTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laTableMouseClicked

        if (laTable.getSelectedRow() != -1) {
            btnModifierVIP.setEnabled(true);
        }
    }//GEN-LAST:event_laTableMouseClicked

    private void btPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPhotoActionPerformed
        try {
            FenetrePhoto ajoutPhoto = new FenetrePhoto(this);
            ajoutPhoto.doModal();
        } catch (Exception ex) {
            System.out.println(" Erreur au chargement : " + ex.getMessage());
        }
    }//GEN-LAST:event_btPhotoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInserer;
    private javax.swing.JButton btPhoto;
    private javax.swing.JButton btnModifierVIP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpGestion;
    private javax.swing.JTable laTable;
    // End of variables declaration//GEN-END:variables
}
