package ihm;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import metier.Vip;
import modele.ModeleJTable;
import application.Appli;

public class FenetreApplication extends javax.swing.JFrame {

    private ModeleJTable leModele;

    public FenetreApplication() throws Exception {
        
        
        // instanciation du modele de données de la JTable
        this.leModele = new ModeleJTable();
        // initialisation des composants
        initComponents();
        Appli.centreWindow(this);
        // affichage
        try {
            leModele.chargerLesVips();
        } catch (SQLException ex) {
            System.out.println(" Erreur au chargement : " + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        laTable = new javax.swing.JTable();
        jpGestion = new javax.swing.JPanel();
        btInserer = new javax.swing.JButton();
        btSupprimer = new javax.swing.JButton();
        btnModifierVIP = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("VIPs");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        laTable.setModel(leModele);
        laTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        laTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                laTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(laTable);

        jpGestion.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)), "Gestion", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 10))); // NOI18N

        btInserer.setText("Inserer");
        btInserer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsererActionPerformed(evt);
            }
        });

        btSupprimer.setText("Supprimer");
        btSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSupprimerActionPerformed(evt);
            }
        });

        btnModifierVIP.setText("Modifier VIP");
        btnModifierVIP.setEnabled(false);
        btnModifierVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierVIPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpGestionLayout = new javax.swing.GroupLayout(jpGestion);
        jpGestion.setLayout(jpGestionLayout);
        jpGestionLayout.setHorizontalGroup(
            jpGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGestionLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(btInserer, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(btnModifierVIP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btSupprimer)
                .addGap(78, 78, 78))
        );
        jpGestionLayout.setVerticalGroup(
            jpGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpGestionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpGestionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInserer)
                    .addComponent(btSupprimer)
                    .addComponent(btnModifierVIP))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 781, Short.MAX_VALUE)
                    .addComponent(jpGestion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpGestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSupprimerActionPerformed
        // TODO add your handling code here:
        /*int ligne = laTable.getSelectedRow();
        if (ligne != -1) {
            try {
                leModele.supprimerEmploye(ligne);
            } catch (SQLException e) {
                System.out.println("Erreur à la suppression : " + e.getMessage());
            }
        }*/
    }//GEN-LAST:event_btSupprimerActionPerformed

    private void btInsererActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsererActionPerformed
        Vip vip = new Vip(0, null, null, null);
        FenetreSaisieVip laSaisie = new FenetreSaisieVip(this, vip);
        if (laSaisie.doModal() == true) {
                try {
                    leModele.chargerLesVips();
                } catch (Exception e) {
                    System.out.println("pas possible");
                }
        }
    }//GEN-LAST:event_btInsererActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez vraiment sortir ?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if (reponse == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnModifierVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierVIPActionPerformed

            int ligneSelectionne = laTable.getSelectedRow();
            //on récupére la valeur de la première colonne de la ligne sélectionné
            int numero = (int)laTable.getValueAt(ligneSelectionne, 0);
            
            FenetreMariageVIP fMariage = null;
            try {
                fMariage = new FenetreMariageVIP(this,numero);
            }
            catch (Exception e) {
                System.out.println(e.getMessage());
            }
            fMariage.doModal();
            
    }//GEN-LAST:event_btnModifierVIPActionPerformed

    private void laTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_laTableMouseClicked
          
        if(laTable.getSelectedRow() != -1){
            btnModifierVIP.setEnabled(true);
        }
    }//GEN-LAST:event_laTableMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btInserer;
    private javax.swing.JButton btSupprimer;
    private javax.swing.JButton btnModifierVIP;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpGestion;
    private javax.swing.JTable laTable;
    // End of variables declaration//GEN-END:variables
}
